name: Build and Publish on DEV

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant to deploy'
        required: true
        type: choice
        options:
          - agaile
          - zohlar
      tag:
        description: 'The container tag to use for deployment'
        required: true
        default: 'latest'
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
        default: 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # Add this step before docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Poetry setup
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      # Authenticate to AWS and ECR
      - name: Authenticate to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: eu-central-1
          LANGGRAPH_API_URL: ${{ secrets.LANGGRAPH_API_URL }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID: ${{ secrets.NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      - name: Set Tenant Variables
        id: tenant-vars
        run: |
          TENANT="${{ github.event.inputs.tenant }}"
          ENV="production"
          
          # Debug output
          echo "Processing tenant: $TENANT for environment: $ENV"
          
          # Use more specific jq path
          TENANT_CONFIG=$(jq -r --arg TENANT "$TENANT" '.dev.tenants[$TENANT]' tenants.json)
          
          if [ $? -eq 0 ] && [ "$TENANT_CONFIG" != "null" ]; then
            echo "PROJECT_NAME=$(echo "$TENANT_CONFIG" | jq -r '.project_name')" >> $GITHUB_OUTPUT
            echo "ASSISTANT_ID=$(echo "$TENANT_CONFIG" | jq -r '.assistant_id')" >> $GITHUB_OUTPUT
          else
            echo "Error: Could not find tenant configuration for $TENANT"
            exit 1
          fi

      - name: Validate Environment Variables
        run: |
          required_vars=(
            "LANGCHAIN_API_KEY"
            "LANGGRAPH_API_URL"
            "AWS_ACCESS_KEY_ID_DEV"
            "AWS_SECRET_ACCESS_KEY_DEV"
          )
          
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set"
              exit 1
            fi
          done
          
          # Validate assistant ID from tenant config
          if [ -z "${{ steps.tenant-vars.outputs.ASSISTANT_ID }}" ]; then
            echo "Error: Assistant ID not found in tenants.json for tenant ${{ github.event.inputs.tenant }}"
            exit 1
          fi
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID_DEV: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LANGGRAPH_API_URL: ${{ secrets.LANGGRAPH_API_URL }}

      - name: Build and Push Docker Image
        run: |
          echo "Building and pushing Docker image for tenant ${{ github.event.inputs.tenant }}..."
          
          # Define variables
          IMAGE_NAME=cap-frontend
          TENANT_NAME=${{ steps.tenant-vars.outputs.PROJECT_NAME }}
          TAG=${{ github.event.inputs.tag }}
          DOCKERFILE_PATH=${{ github.event.inputs.dockerfile || 'Dockerfile' }}
          ECR_REGISTRY=533267288999.dkr.ecr.eu-central-1.amazonaws.com
          ENV="production"
          
          # Debug output
          echo "Environment variables:"
          echo "ENV_NAME=${ENV}"
          echo "NEXT_PUBLIC_APP_ENV=${ENV}"
          echo "NODE_ENV=production"
          
          # Combine tenant name and tag if tag is not 'latest'
          if [ "$TAG" != "latest" ]; then
            FINAL_TAG="${TENANT_NAME}-${TAG}"
          else
            FINAL_TAG="${TENANT_NAME}"
          fi
          
          # Build the Docker image with buildx
          docker buildx build \
            --platform linux/arm64 \
            --build-arg LANGCHAIN_API_KEY="${LANGCHAIN_API_KEY}" \
            --build-arg LANGGRAPH_API_URL="${LANGGRAPH_API_URL}" \
            --build-arg NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID="${{ steps.tenant-vars.outputs.ASSISTANT_ID }}" \
            --build-arg NEXT_PUBLIC_APP_ENV="${ENV}" \
            --build-arg TENANT_NAME="${{ github.event.inputs.tenant }}" \
            --build-arg ENV_NAME="${ENV}" \
            --push \
            -t $ECR_REGISTRY/$IMAGE_NAME:$FINAL_TAG .
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LANGGRAPH_API_URL: ${{ secrets.LANGGRAPH_API_URL }}

      - name: Debug Build Info
        run: |
          echo "Building for:"
          echo "Tenant: ${{ github.event.inputs.tenant }}"
          echo "Environment: ${ENV}"
          echo "Tag: ${TAG}"
          echo "Registry: ${ECR_REGISTRY}"